Routes/web.php
                Route::get('members/need-approval', 'MemberRegistrationController@needApproval')->name('need-approval');
                Route::get('members/need-approval/data', 'MemberRegistrationController@needApprovalData')->name('need-approval.data');
                /* Member Waiting Payment */
                Route::get('members/waiting-payment', 'MemberRegistrationController@waitingPayment')->name('waiting-payment')->middleware('permission:member-waiting-payment');
                Route::get('members/waiting-payment/data', 'MemberRegistrationController@waitingPaymentData')->name('waiting-payment.data')->middleware('permission:member-waiting-payment');
                Route::get('members/edit/email', 'MemberRegistrationController@editEmailForm')->name('edit-email');
                Route::patch('members/edit/email/{id}', 'MemberRegistrationController@editEmailSave')->name('edit-email.save');
                Route::get('members/resend/email-registration', 'MemberRegistrationController@resendEmailRegistrationForm')->name('resend-email');
                Route::patch('members/resend/email-registration/{id}', 'MemberRegistrationController@resendEmailRegistrationSave')->name('resend-email.save');
                Route::get('members/upload-bukti-transfer', 'MemberRegistrationController@uploadBuktiTransferForm')->name('upload-bukti-transfer');
                Route::patch('members/upload-bukti-transfer/{id}', 'MemberRegistrationController@uploadBuktiTransferSave')->name('upload-bukti-transfer.save');
                Route::delete('members/upload-bukti-transfer/delete-file', 'MemberRegistrationController@uploadBuktiTransferDeleteSave')->name('upload-bukti-transfer.delete-file.save');
                Route::get('members/upload-bukti-transfer/delete-file', 'MemberRegistrationController@uploadBuktiTransferDeleteForm')->name('upload-bukti-transfer.delete-file');

                /* approve payment confirmation */
                Route::get('members/payment/approve/confirmation', 'MemberRegistrationController@paymentApprovalConfirmation')->name('payment.approve.confirmation');
                Route::patch('members/payment/approve/confirmation/{id}', 'MemberRegistrationController@paymentApprovalConfirmationSave')->name('payment.approve.confirmation.save');
                /* Send No. Member Information to Email */
                Route::post('members/{id}/email', 'MemberRegistrationController@sendEmailMember')->name('email');
                /* Check Nomor Member */
                Route::get('members/check/nomember', 'MemberRegistrationController@checkNoMember')->name('check.nomember');
            });

            Route::prefix('tests')->group(function() {

                Route::prefix('info')->group(function() {

                    Route::name('member.test.')->group(function() {

                        Route::get('/', 'MemberTestController@index')->name('index');
                        Route::get('data', 'MemberTestController@indexData')->name('index.data');
                        Route::get('create', 'MemberTestController@create')->name('create');
                        Route::post('create', 'MemberTestController@store')->name('store');
                        Route::get('edit', 'MemberTestController@edit')->name('edit');
                        Route::patch('edit', 'MemberTestController@update')->name('update');
                        Route::get('{id}/show', 'MemberTestController@show')->name('show');
                        Route::get('delete', 'MemberTestController@delete')->name('delete');
                        Route::delete('destroy', 'MemberTestController@destroy')->name('destroy');
                        Route::get('import', 'MemberTestController@importForm')->name('import');
                        Route::post('import', 'MemberTestController@importSave')->name('import.save');

                        Route::get('data-detail', 'MemberTestController@testData')->name('data');

                    });

                });

                Route::prefix('result')->group(function() {

                    Route::name('member.test.result.')->group(function() {

                        Route::get('/', 'MemberTestResultController@index')->name('index');
                        Route::get('data', 'MemberTestResultController@indexData')->name('index.data');
                        Route::get('create', 'MemberTestResultController@create')->name('create');
                        Route::post('create', 'MemberTestResultController@store')->name('store');
                        Route::get('edit', 'MemberTestResultController@edit')->name('edit');
                        Route::patch('edit', 'MemberTestResultController@update')->name('update');
                        Route::get('{id}/show', 'MemberTestResultController@show')->name('show');
                        Route::get('delete', 'MemberTestResultController@delete')->name('delete');
                        Route::delete('destroy', 'MemberTestResultController@destroy')->name('destroy');
                        Route::get('import', 'MemberTestResultController@importForm')->name('import');
                        Route::post('import', 'MemberTestResultController@importSave')->name('import.save');

                        Route::get('data-detail', 'MemberTestResultController@testData')->name('data');

                    });

                });

            });

            Route::name('candidate.')->group(function() {
                Route::get('candidate', 'FormulirKaryawanController@index')->name('index');
                Route::get('candidate/data', 'FormulirKaryawanController@indexData')->name('index.data');
                Route::get('candidate/show/{pub_id}', 'FormulirKaryawanController@show')->name('show');
                Route::delete('candidate/bulk', 'FormulirKaryawanController@destroyBulk')->name('destroy.bulk');
                Route::delete('candidate/{pub_id}', 'FormulirKaryawanController@destroy')->name('destroy');
                Route::get('candidate/excel', 'FormulirKaryawanController@exportExcel')->name('excel');
            });

            Route::name('report.')->group(function() {
                Route::get('reports', 'MemberReportController@index')->name('index');
                Route::get('reports/member-per-day', 'MemberReportController@memberPerDayChart')->name('chart');
            });

            Route::name('membership.setting.')->group(function() {
                Route::get('settings', 'SettingsController@index')->name('index');
                Route::post('settings', 'SettingsController@store')->name('store');
            });
        });
    });
});

    /* Member Registration Process at Frontend */
    Route::get('member/form', 'Frontend\MemberRegistrationController@registrationFormOld')->name('member.register.form');
    Route::get('member/register', 'Frontend\MemberRegistrationController@registrationForm')->name('member.register.index');
    Route::post('member/form/upload', 'Frontend\MemberRegistrationController@formUpload')->name('member.register.form.upload');
    Route::post('member/save', 'Frontend\MemberRegistrationController@registrationSave')->name('member.register.save');
    Route::get('member/check/nik', 'Frontend\MemberRegistrationController@checkNIK')->name('member.register.check.nik');
    Route::get('member/check/email', 'Frontend\MemberRegistrationController@checkEmail')->name('member.register.check');
    Route::get('member/thanks/{pub_id}', 'Frontend\MemberRegistrationController@registrationThanks')->name('member.register.thanks');
    /* Member Test */
    Route::get('member/test', 'MemberTestController@testInfo')->name('member.test.info');
    Route::get('member/test-result', 'MemberTestResultController@testInfo')->name('member.test.result.info');
    /* Member Registration Payment Confirmation */
    Route::post('member/registration/confirmation', 'Frontend\MemberRegistrationController@paymentConfirmationStore')->name('member.register.confirm.store');
    Route::get('member/registration/confirmation/{id}', 'Frontend\MemberRegistrationController@paymentConfirmation')->name('member.register.confirm');
    Route::patch('member/registration/confirmation/update/{id}', 'Frontend\MemberRegistrationController@paymentConfirmationUpdate')->name('member.register.confirm.update');
    Route::get('member/registration/thanks/{pubid}', 'Frontend\MemberRegistrationController@paymentConfirmationThanks')->name('member.register.confirm.thanks');
    /* File Uploader */
    Route::get('document/uploader', 'Frontend\DocumentUploaderController@create')->name('document.uploader.create');
    Route::post('document/uploader', 'Frontend\DocumentUploaderController@store')->name('document.uploader.store');
    Route::delete('document/uploader', 'Frontend\DocumentUploaderController@destroy')->name('document.uploader.destroy');

    Route::prefix('candidate')->group(function() {
        Route::name('candidate.')->group(function() {
            Route::get('iei/form', 'FormulirKaryawanController@create')->name('form');
            Route::post('iei/save', 'FormulirKaryawanController@store')->name('save');
            Route::get('iei/check/nik', 'FormulirKaryawanController@checkNIK')->name('check.nik');
            Route::get('iei/check/email', 'FormulirKaryawanController@checkEmail')->name('check.email');
            Route::get('iei/thanks/{pub_id}', 'FormulirKaryawanController@registrationThanks')->name('thanks');
        });
    });

    Route::prefix('demo')->group(function() {
        Route::get('member/form', 'Frontend\MemberRegistrationController@registrationFormDemo');
        Route::get('member/check/nik', 'MemberRegistrationController@checkNIK');
        Route::get('member/check/email', 'MemberRegistrationController@checkEmail');
    });

    Route::get('agg/member/active', 'Admin\Report\MemberAggregateController@memberAggActiveInitialDate');

Resources/views/karyawan/index.blade.php
@extends('memberregistration::layouts.master')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="box-title"></h3>
                        </div>
                        <div class="col-md-6">
                            <div class="box-tools pull-right">
                                @can('member-delete')
                                <button class="btn btn-sm btn-danger hide" id="bulk_delete">
                                    <i class="fa fa-trash"></i>
                                    Delete
                                </button>
                                @endcan
                                {{-- @can('candidate-create') --}}
                                <a class="btn btn-sm btn-warning" href="{!! route('candidate.form') !!}" target="_blank">
                                    <i class="fa fa-file-text-o"></i> Form
                                </a>
                                {{-- <a class="btn btn-sm btn-primary" href="{!! route('member.create') !!}">
                                    <i class="fa fa-plus"></i> Member Baru
                                </a> --}}
                                {{-- @if($data->count() > 0) --}}
                                <a class="btn btn-sm btn-success" href="{!! route('candidate.excel') !!}">
                                    <i class="fa fa-file-excel-o"></i> Excel
                                </a>
                                {{-- @endif --}}
                                {{-- @endcan --}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-body" style="min-height: 520px">
                    <div class="row">
                        <div class="col-md-6"></div>
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4 col-xs-6">
                                    <div class="form-group">
                                        <label for="start_date" class="small">Start Date</label>
                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            {!! Form::text('start_date', $startDate, [ 'class' => 'form-control datepicker input-sm', 'id' => 'start_date']) !!}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4 col-xs-6 pull-right">
                                    <div class="form-group">
                                        <label for="end_date" class="small">End Date</label>
                                        <div class="input-group date">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            {!! Form::text('end_date', $endDate, [ 'class' => 'form-control datepicker input-sm', 'id' => 'end_date']) !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <table id="grid-karyawan" class="table table-bordered table-striped table-responsive" style="width:100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th class="text-center" style="width: 2%">#</th>
                                <th class="text-center">NIK</th>
                                <th class="text-center">Nama Lengkap</th>
                                <th class="text-center" style="width: 7%">Tgl. Lahir</th>
                                <th class="text-center">Kota/Kab.</th>
                                <th class="text-center">Pendidikan</th>
                                <th class="text-center">Jurusan</th>
                                <th class="text-center">JK</th>
                                <th class="text-center">Email</th>
                                <th class="text-center" style="width: 100px">Tgl. Daftar</th>
                                <th class="text-center" style="width: 5%">
                                    <i class="fa fa-navicon"></i>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .datepicker table tr td.disabled{
            color:red;
            cursor: not-allowed;
        }
        .datepicker table tr td.today{
            background: orange;
        }
        .datepicker table tr td.active{
            font-weight: bold;
        }
    </style>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            var btnBulkDelete = $('#bulk_delete');
            var startDate = $('#start_date');
            var endDate = $('#end_date');

            var table = $("#grid-karyawan").DataTable({
                processing: true,
                serverSide: true,
                responsive: false,
                paging: true,
                keys: false,
                scrollX: true,
                dom: '<"row"<"col-md-4"l><"col-md-4 text-center"B><"col-md-4"f>>' + 'rtip',
                select: {
                    style: 'os',
                    selector: 'td:first-child'
                },
                buttons: [
                    {
                        extend: 'selectAll',
                        text: 'Select All',
                        className: "btn-sm",
                    },
                    {
                        extend:'selectNone',
                        text: 'Select None',
                        className: "btn-sm",
                    },
                    {
                        text: '<i class="fa fa-refresh"></i> Refresh',
                        className: "btn-sm",
                        action: function(e, dt, node, config) {
                            dt.ajax.reload();
                        }
                    }
                ],
                ajax: { 
                    url: "{!! route('candidate.index.data') !!}",
                    data: function(d) {
                        d.start_date = startDate.val();
                        d.end_date = endDate.val();
                    }
                },
                columns: [
                    {data: 'checkboxes', name: 'checkboxes', orderable: false, searchable: false},
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', className: "small", orderable: false, searchable: false},
                    {data: 'nik', name: 'nik', className: "small"},
                    {data: 'fullname', name: 'fullname', className: "small"},
                    {data: 'tgl_lahir', name: 'tgl_lahir', className: "small"},
                    {data: 'kabupaten', name: 'kabupaten', className: "small"},
                    {data: 'sekolah', name: 'sekolah', className: "small"},
                    {data: 'jurusan', name: 'jurusan', className: "small"},
                    {data: 'gender', name: 'gender', className: "small text-center"},
                    {data: 'email', name: 'email', className: "small"},
                    {data: 'created_at', name: 'created_at', className: "small"},
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ],
                columnDefs: [
                    {
                        targets: 0,
                        className: 'select-checkbox'
                    },
                    {targets: 4, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY' )},
                    {targets: 10, render: $.fn.dataTable.render.moment('YYYY-MM-DD HH:mm:ss', 'DD-MM-YYYY HH:mm:ss' )}
                ],
                order: [[ 10, 'desc' ]],
                language: {
                    processing: "<p class='text-center'>Loading...</p>"
                },
            });

            table.on( 'select', function ( e, dt, type, indexes ) {
                var count = table.rows( { selected: true } ).count();
                if ( count > 0 ) {
                    btnBulkDelete.removeClass('hide');
                }
            } );

            table.on( 'deselect', function ( e, dt, type, indexes ) {
                var count = table.rows( { selected: true } ).count();
                if ( count === 0 ) {
                    btnBulkDelete.addClass('hide');
                }
            } );

            btnBulkDelete.on('click', function(e) {
                e.preventDefault();
                var countRows = table.rows( { selected: true } ).data().count();
                swal({
                    title: 'Confirmation',
                    text: 'Are you sure you want to delete this ' + countRows + ' row(s)?',
                    buttons: ["Cancel", "Yes"],
                    dangerMode: true,
                    closeOnClickOutside: false,
                }).then(function(value) {
                    if(value) {
                        var selectedRows = table.rows( { selected: true } ).data().to$();
                        var selectedId = Array();
                        $.each(selectedRows, function(i, e) {
                            selectedId.push(e.id);
                        });

                        $.ajax({
                            url: "{!! route('candidate.destroy.bulk') !!}",
                            type: "post",
                            data: {
                                _method: "delete",
                                _token: "{!! csrf_token() !!}",
                                id: selectedId,
                            },
                            success: function(res, stat, xhr) {
                                swal({
                                    text: res.message,
                                    icon: 'success',
                                    button: 'close',
                                    closeOnClickOutside: false,
                                });
                                table.draw();
                                btnBulkDelete.addClass('hide');
                            },
                            error: function(err) {
                                swal({
                                    text: err,
                                    icon: 'error',
                                    button: 'close',
                                    closeOnClickOutside: false,
                                });
                            }
                        });
                    }
                });

            });

            $('.datepicker').datepicker({
                format: 'dd-mm-yyyy',
                autoclose: true,
                todayHighlight: true,
                weekStart: 1,
                endDate: '+0d',
                language: 'id'
            });

            $('.dataTables_scrollBody').css('height', '350px');

            startDate.on('change', function(e) {
                e.preventDefault();
                getDataMember();
            });

            endDate.on('change', function(e) {
                e.preventDefault();
                getDataMember();
            });

            function getDataMember() {
                $.ajax({
                    url: "{!! route('candidate.index.data') !!}",
                    type: "GET",
                    data: { 
                        start_date: startDate.val(),
                        end_date: endDate.val(),
                    },
                    success: function(data) {
                        table.ajax.reload();
                    }
                });
            }
        });
    </script>
@endsection