Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function () {

    Route::prefix('manage')->group(function() {

        Route::prefix('membership')->group(function() {

            Route::name('member.')->group(function() {
                Route::get('members', 'MemberRegistrationController@index')->name('index');
                Route::get('members/data', 'MemberRegistrationController@indexData')->name('index.data');
                Route::get('members/create', 'MemberRegistrationController@create')->name('create');
                Route::post('members/store', 'MemberRegistrationController@store')->name('store');
                Route::get('members/{id}/show', 'MemberRegistrationController@show')->name('show');
                Route::get('members/{id}/edit', 'MemberRegistrationController@edit')->name('edit');
                Route::patch('members/{id}', 'MemberRegistrationController@update')->name('update');
                Route::delete('members/bulk', 'MemberRegistrationController@destroyBulk')->name('destroy.bulk');
                Route::delete('members/{id}', 'MemberRegistrationController@destroy')->name('destroy');
                Route::get('members/{id}/print', 'MemberRegistrationController@print')->name('print');
                Route::get('members/{id}/print/pdf', 'MemberRegistrationController@printPdf')->name('print.pdf');
                Route::get('members/excel', 'MemberRegistrationController@exports')->name('exports');

                Route::get('members/show', 'MemberRegistrationController@showModal')->name('show.modal');

                /* Member Active */
                Route::get('members/active-member', 'MemberRegistrationController@activeMember')->name('active-member');
                Route::get('members/active-member/data', 'MemberRegistrationController@activeMemberData')->name('active-member.data');
                /* Member Need Approval */
                Route::get('members/need-approval', 'MemberRegistrationController@needApproval')->name('need-approval');
                Route::get('members/need-approval/data', 'MemberRegistrationController@needApprovalData')->name('need-approval.data');
                /* Member Waiting Payment */
                Route::get('members/waiting-payment', 'MemberRegistrationController@waitingPayment')->name('waiting-payment')->middleware('permission:member-waiting-payment');
                Route::get('members/waiting-payment/data', 'MemberRegistrationController@waitingPaymentData')->name('waiting-payment.data')->middleware('permission:member-waiting-payment');
                Route::get('members/edit/email', 'MemberRegistrationController@editEmailForm')->name('edit-email');
                Route::patch('members/edit/email/{id}', 'MemberRegistrationController@editEmailSave')->name('edit-email.save');
                Route::get('members/resend/email-registration', 'MemberRegistrationController@resendEmailRegistrationForm')->name('resend-email');
                Route::patch('members/resend/email-registration/{id}', 'MemberRegistrationController@resendEmailRegistrationSave')->name('resend-email.save');
                Route::get('members/upload-bukti-transfer', 'MemberRegistrationController@uploadBuktiTransferForm')->name('upload-bukti-transfer');
                Route::patch('members/upload-bukti-transfer/{id}', 'MemberRegistrationController@uploadBuktiTransferSave')->name('upload-bukti-transfer.save');
                Route::delete('members/upload-bukti-transfer/delete-file', 'MemberRegistrationController@uploadBuktiTransferDeleteSave')->name('upload-bukti-transfer.delete-file.save');
                Route::get('members/upload-bukti-transfer/delete-file', 'MemberRegistrationController@uploadBuktiTransferDeleteForm')->name('upload-bukti-transfer.delete-file');

                /* approve payment confirmation */
                Route::get('members/payment/approve/confirmation', 'MemberRegistrationController@paymentApprovalConfirmation')->name('payment.approve.confirmation');
                Route::patch('members/payment/approve/confirmation/{id}', 'MemberRegistrationController@paymentApprovalConfirmationSave')->name('payment.approve.confirmation.save');
                /* Send No. Member Information to Email */
                Route::post('members/{id}/email', 'MemberRegistrationController@sendEmailMember')->name('email');
                /* Check Nomor Member */
                Route::get('members/check/nomember', 'MemberRegistrationController@checkNoMember')->name('check.nomember');
            });

            Route::prefix('tests')->group(function() {

                Route::prefix('info')->group(function() {

                    Route::name('member.test.')->group(function() {

                        Route::get('/', 'MemberTestController@index')->name('index');
                        Route::get('data', 'MemberTestController@indexData')->name('index.data');
                        Route::get('create', 'MemberTestController@create')->name('create');
                        Route::post('create', 'MemberTestController@store')->name('store');
                        Route::get('edit', 'MemberTestController@edit')->name('edit');
                        Route::patch('edit', 'MemberTestController@update')->name('update');
                        Route::get('{id}/show', 'MemberTestController@show')->name('show');
                        Route::get('delete', 'MemberTestController@delete')->name('delete');
                        Route::delete('destroy', 'MemberTestController@destroy')->name('destroy');
                        Route::get('import', 'MemberTestController@importForm')->name('import');
                        Route::post('import', 'MemberTestController@importSave')->name('import.save');

                        Route::get('data-detail', 'MemberTestController@testData')->name('data');

                    });

                });

                Route::prefix('result')->group(function() {

                    Route::name('member.test.result.')->group(function() {

                        Route::get('/', 'MemberTestResultController@index')->name('index');
                        Route::get('data', 'MemberTestResultController@indexData')->name('index.data');
                        Route::get('create', 'MemberTestResultController@create')->name('create');
                        Route::post('create', 'MemberTestResultController@store')->name('store');
                        Route::get('edit', 'MemberTestResultController@edit')->name('edit');
                        Route::patch('edit', 'MemberTestResultController@update')->name('update');
                        Route::get('{id}/show', 'MemberTestResultController@show')->name('show');
                        Route::get('delete', 'MemberTestResultController@delete')->name('delete');
                        Route::delete('destroy', 'MemberTestResultController@destroy')->name('destroy');
                        Route::get('import', 'MemberTestResultController@importForm')->name('import');
                        Route::post('import', 'MemberTestResultController@importSave')->name('import.save');

                        Route::get('data-detail', 'MemberTestResultController@testData')->name('data');

                    });

                });

            });

            Route::name('candidate.')->group(function() {
                Route::get('candidate', 'FormulirKaryawanController@index')->name('index');
                Route::get('candidate/data', 'FormulirKaryawanController@indexData')->name('index.data');
                Route::get('candidate/show/{pub_id}', 'FormulirKaryawanController@show')->name('show');
                Route::delete('candidate/bulk', 'FormulirKaryawanController@destroyBulk')->name('destroy.bulk');
                Route::delete('candidate/{pub_id}', 'FormulirKaryawanController@destroy')->name('destroy');
                Route::get('candidate/excel', 'FormulirKaryawanController@exportExcel')->name('excel');
            });

            Route::name('report.')->group(function() {
                Route::get('reports', 'MemberReportController@index')->name('index');
                Route::get('reports/member-per-day', 'MemberReportController@memberPerDayChart')->name('chart');
            });

            Route::name('membership.setting.')->group(function() {
                Route::get('settings', 'SettingsController@index')->name('index');
                Route::post('settings', 'SettingsController@store')->name('store');
            });
        });
    });
});

    /* Member Registration Process at Frontend */
    Route::get('member/form', 'Frontend\MemberRegistrationController@registrationFormOld')->name('member.register.form');
    Route::get('member/register', 'Frontend\MemberRegistrationController@registrationForm')->name('member.register.index');
    Route::post('member/form/upload', 'Frontend\MemberRegistrationController@formUpload')->name('member.register.form.upload');
    Route::post('member/save', 'Frontend\MemberRegistrationController@registrationSave')->name('member.register.save');
    Route::get('member/check/nik', 'Frontend\MemberRegistrationController@checkNIK')->name('member.register.check.nik');
    Route::get('member/check/email', 'Frontend\MemberRegistrationController@checkEmail')->name('member.register.check');
    Route::get('member/thanks/{pub_id}', 'Frontend\MemberRegistrationController@registrationThanks')->name('member.register.thanks');
    /* Member Test */
    Route::get('member/test', 'MemberTestController@testInfo')->name('member.test.info');

Entities/Member.php
<?php

namespace Modules\MemberRegistration\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Member extends Model
{
    use Notifiable;
    
    protected $dates    = ['tgl_lahir', 'reg_date'];
    protected $fillable = [
        'pub_id',
        'id_member',
        'full_name',
        'nik',
        'email',
        'no_hp',
        'no_wa',
        'tmp_lahir',
        'tgl_lahir',
        'gender',
        'blood_type',
        'tb',
        'bb',
        'alamat',
        'kabupaten',
        'provinsi',
        'kodepos',
        'jenjang',
        'sekolah',
        'jurusan',
        'thn_lulus',
        'exp_company_1',
        'exp_position_1',
        'exp_duration_year_1',
        'exp_duration_month_1',
        'exp_company_2',
        'exp_position_2',
        'exp_duration_year_2',
        'exp_duration_month_2',
        'status',
        'skills',
        'id_card',
        'pas_foto',
        'reg_date',
        'is_active',
        'mail_to_member',
        'approved_date',
        'approved_by'
    ];

    public function rel_provinsi() {
        return $this->belongsTo('App\Models\Master\Provinsi', 'provinsi', 'code');
    }

    public function has_subs() {
        return $this->hasOne('Modules\MemberRegistration\Entities\MemberSubscription', 'pub_id', 'pub_id');
    }

    public function rel_user() {
        return $this->belongsTo('App\Models\User', 'approved_by');
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($member) {
            $member->has_subs()->delete();
        });
    }
}

Resources/views/members/modals/delete-file.blade.php
{!! Form::hidden('id', $data->id, ['id' => 'file_id']) !!}
{!! Form::hidden('token', csrf_token(), ['id' => 'token']) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Confirmation Delete </h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-sm-12">
            <span>Apakah anda yakin akan menghapus file bukti transfer dari <strong>{!! $data->full_name !!}</strong>?</span>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-danger" id="submit_delete"><i class="fa fa-trash"></i> Delete</button>
</div>
<script>
    $(document).ready(function() {
        $("#submit_delete").on('click', function(e) {
            let id = $('#file_id').val();
            let token = $('#token').val();
            $.ajax({
                type: "POST",
                url: "{!! route('member.upload-bukti-transfer.delete-file.save') !!}",
                data: {
                    id: id,
                    _method: 'DELETE',
                    _token: token
                },
                success: function(data) {
                    $("#confirmation").modal('hide');
                    toastr.success(data.message);
                    $("#file_image").addClass('hide');
                    $("#file_input").removeClass('hide');
                },
                error: function(error) {
                    toastr.error(error.message);
                }
            });
        });
    });
</script>

Resources/views/members/modals/edit-email.blade.php
<form id="member_email_edit" class="form-horizontal">
    @csrf
    {!! Form::hidden('_method', 'PATCH') !!}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Edit Email</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label for="old_email" class="col-sm-4 control-label">Email Lama </label>
                    <div class="col-sm-6">
                        {!! Form::text('old_email', $data->email, [ 'class' => 'form-control input-sm', 'id' => 'old_email', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label for="new_email" class="col-sm-4 control-label">Email Baru <span class="required">*</span></label>
                    <div class="col-sm-6">
                        {!! Form::email('new_email', null, [ 'class' => 'form-control input-sm', 'id' => 'new_email', 'required', 'autofocus']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" id="submit"> Update</button>
    </div>
</form>
<style>
    .errors {
        color:#FF0000;  /* red */
    }
</style>
<script>
    $(document).ready(function() {
        $("#submit").on('click', function(e) {
            $.validator.addMethod("notEqualTo", function(value, element, param) {
                return this.optional(element) || value != $(param).val();
            }, "email tidak boleh sama");
            $("#member_email_edit").validate({
                errorClass: 'errors small',
                rules: {
                    new_email: {
                        required: true,
                        email: true,
                        notEqualTo: "#old_email"
                    }
                },
                messages: {
                    new_email: {
                        required: 'harus diisi',
                        email: 'email harus benar'
                    }
                },
                submitHandler: function(form) {
                    $.ajax({
                        type: "POST",
                        url: "{!! url('manage/membership/members/edit/email') !!}/{!! $data->id !!}",
                        data: $(form).serialize(),
                        success: function(data) {
                            $("#confirmation").modal('hide');
                            toastr.success(data.message);
                            $('#grid-members').DataTable().ajax.reload(null, false);
                        },
                        error: function(error) {
                            toastr.error(error.message);
                        }
                    });
                }
            });
        });
    });
</script>

Resources/views/members/modals/payment-approval.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Payment Approval</h4>
</div>
<form id="member_payment_approval">
@csrf
{!! Form::hidden('_method', 'PATCH') !!}
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="box-title">Data Tagihan</h4>
                        </div>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            @if(isset($data->has_subs))
                            <div class="table-responsive">
                            <table id="" class="table table-bordered" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th>Biaya Member</th>
                                        <th>Kode Unik</th>
                                        <th>Total Pembayaran</th>
                                        <th>Batas Waktu Pembayaran</th>
                                        <th>Status Pembayaran</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="text-right">{!! isset($data->has_subs->subs_price) ? numberFormat($data->has_subs->subs_price) : null !!}</td>
                                        <td class="text-right">{!! isset($data->has_subs->unique_no) ? $data->has_subs->unique_no : null !!}</td>
                                        <td class="text-right text-bold">{!! numberFormat( (isset($data->has_subs->subs_price) ? $data->has_subs->subs_price : 0) + (isset($data->has_subs->unique_no) ? $data->has_subs->unique_no : 0)) !!}</td>
                                        <td>{!! isset($data->has_subs->payment_due_date) ? date('d-m-Y H:i:s', strtotime($data->has_subs->payment_due_date)) : null !!}</td>
                                        <td><span class="label label-warning">{!! getMemberStatus($data->has_subs->payment_status) !!}</span></td>
                                    </tr>
                                </tbody>
                            </table>
                            </div>
                            @else
                            <span class="text-danger">Belum ada data pembayaran.</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="box-title">Data Pembayaran</h4>
                        </div>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            @if(isset($data->has_subs->has_confirmation))
                            <div class="table-responsive">
                            <table id="" class="table table-bordered" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th>Transfer ke</th>
                                        <th>Jumlah Transfer</th>
                                        <th>Tanggal Transfer</th>
                                        <th>Dari Bank</th>
                                        <th>No. Rekening</th>
                                        <th>Pemegang Rekening</th>
                                        <th>Tanggal Konfirmasi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            @if($data->has_subs->has_confirmation->bank_account_id == 'DKUCMB')
                                                CIMB NIAGA - 800132891100
                                            @endif
                                        </td>
                                        <td>{!! numberFormat($data->has_subs->has_confirmation->transfer_amount) !!}</td>
                                        <td>{!! date('d-m-Y', strtotime($data->has_subs->has_confirmation->transfer_date)) !!}</td>
                                        <td>
                                            {!! $data->has_subs->has_confirmation->bank_rel->name !!}
                                            @if($data->has_subs->has_confirmation->transfer_bank_id == '999')
                                                @if(!empty($data->has_subs->has_confirmation->transfer_bank_name))
                                                    ({!! $data->has_subs->has_confirmation->transfer_bank_name !!})
                                                @endif
                                            @endif
                                        </td>
                                        <td>{!! $data->has_subs->has_confirmation->transfer_bank_account !!}</td>
                                        <td>{!! $data->has_subs->has_confirmation->transfer_bank_holder_name !!}</td>
                                        <td>{!! date('d-m-Y H:i:s', strtotime($data->has_subs->has_confirmation->created_at)) !!}</td>
                                    </tr>
                                </tbody>
                            </table>
                            </div>
                            <div class="table-responsive">
                            <table id="" class="table table-bordered" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th>Bukti Transfer</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            @if(!empty($data->has_subs->has_confirmation->transfer_attachment))
                                                @if(config('memberregistration.disk') == 's3')
                                                    @if(Storage::disk('s3')->exists('members/'.$data->nik.'/'.$data->has_subs->has_confirmation->transfer_attachment))
                                                    <img data-src="{!! Storage::disk('s3')->url('members/'.$data->nik.'/'.$data->has_subs->has_confirmation->transfer_attachment) !!}" src="{!! asset('img/loading-bar.gif') !!}" alt="" style="max-width:400px;max-height:400px;border:1px solid #ECF0F5;border-radius:10px">
                                                    @else
                                                    <img src="{!! asset('storage/members/'.$data->nik.'/'.$data->has_subs->has_confirmation->transfer_attachment) !!}" alt="" style="max-width:500px;max-height:500px;border:1px solid #ECF0F5;border-radius:10px">
                                                    @endif
                                                @endif
                                            @endif
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            </div>
                            @else
                            <span class="text-danger">Belum ada konfirmasi pembayaran.</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label class="col-sm-12 control-label">Apakah anda yakin akan menyetujui pembayaran dari <b>{!! $data->full_name !!}</b>?</label>
        </div>
        <div class="form-group">
            <label for="member_no" class="col-sm-2 control-label">No. Member <span class="required">*</span></label>
            <div class="col-sm-3">
                {!! Form::text('member_no', $data->id_member, [ 'class' => 'form-control input-sm text-uppercase', 'id' => 'member_no', 'maxlength' => 7, 'autocomplete' => 'off', 'autofocus', 'required']) !!}
            </div>
        </div>
        <div class="form-group">
            <label for="approve_date" class="col-sm-2 control-label">Approve Date <span class="required">*</span></label>
            <div class="col-sm-3">
                {!! Form::text('approve_date', date('d-m-Y'), [ 'class' => 'form-control input-sm datepicker', 'id' => 'approve_date', 'autocomplete' => 'off', 'required']) !!}
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" id="submit"><i class="fa fa-check-square-o"></i> Confirm</button>
</div>
</form>
<style>
    .errors {
        color:#FF0000;  /* red */
    }
</style>
<script>
    $(document).ready(function() {
        new EagerImageLoader();
        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
            autoclose: true,
            todayHighlight: true,
            weekStart: 1,
            endDate: '+1d',
            language: 'id'
        });
        $("#submit").on('click', function(e) {
            $("#member_payment_approval").validate({
                errorClass: 'errors small',
                rules: {
                    member_no: {
                        required: true,
                        digits: true,
                        maxlength: 7,
                        minlength: 5,
                        remote: {
                            url: "check/nomember"
                        }
                    },
                    approve_date: {
                        required: true
                    }
                },
                messages: {
                    member_no: {
                        required: "harus diisi.",
                        digits: "harus angka",
                        maxlength: "harus 7 digit",
                        minlength: "harus 5 digit",
                        remote: "No. Member sudah dipakai."
                    },
                    approve_date: {
                        required: "harus diisi."
                    }
                },
                submitHandler: function(form) {
                    $.ajax({
                        type: "POST",
                        url: "{!! url('manage/membership/members/payment/approve/confirmation') !!}/{!! $data->id !!}",
                        data: $(form).serialize(),
                        success: function(data) {
                            $("#detail").modal('hide');
                            toastr.success(data.message);
                            $('#grid-members').DataTable().ajax.reload(null, false);
                        },
                        error: function(error) {
                            toastr.error(error.message);
                        }
                    });
                }
            });
        });
    });
</script>

Resources/views/members/modals/resend-email-registration.blade.php
<form id="member_resend_email" class="form-horizontal">
    @csrf
    {!! Form::hidden('_method', 'PATCH') !!}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Resend Email Registration</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label for="full_name" class="col-sm-4 control-label">Nama Lengkap </label>
                    <div class="col-sm-6">
                        {!! Form::text('full_name', $data->full_name, [ 'class' => 'form-control input-sm', 'id' => 'full_name', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-sm-4 control-label">Email </label>
                    <div class="col-sm-6">
                        {!! Form::email('email', $data->email, [ 'class' => 'form-control input-sm', 'id' => 'email', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label for="subs_price" class="col-sm-4 control-label">Biaya Member </label>
                    <div class="col-sm-6">
                        {!! Form::text('subs_price', numberFormat($data->has_subs->subs_price + $data->has_subs->unique_no), [ 'class' => 'form-control input-sm', 'id' => 'subs_price', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label for="reg_date" class="col-sm-4 control-label">Daftar </label>
                    <div class="col-sm-6">
                        {!! Form::text('reg_date', dateFormatDmyHi($data->created_at), [ 'class' => 'form-control input-sm', 'id' => 'reg_date', 'readonly']) !!}
                    </div>
                </div>
                <div class="form-group">
                    <label for="due_date" class="col-sm-4 control-label">Jatuh Tempo </label>
                    <div class="col-sm-6">
                        {!! Form::text('due_date', dateFormatDmyHi($data->has_subs->payment_due_date), [ 'class' => 'form-control input-sm', 'id' => 'due_date', 'readonly']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" id="submit"><i class="fa fa-send"></i> Send</button>
    </div>
</form>
<style>
    .errors {
        color:#FF0000;  /* red */
    }
</style>
<script>
    $(document).ready(function() {
        $("#submit").on('click', function(e) {
            $("#member_resend_email").validate({
                errorClass: 'errors small',
                rules: { },
                messages: { },
                submitHandler: function(form) {
                    $.ajax({
                        type: "POST",
                        url: "{!! url('manage/membership/members/resend/email-registration') !!}/{!! $data->id !!}",
                        data: $(form).serialize(),
                        success: function(data) {
                            $("#confirmation").modal('hide');
                            toastr.success(data.message);
                        },
                        error: function(error) {
                            toastr.error(error.message);
                        }
                    });
                }
            });
        });
    });
</script>